Title: "Open Coding Society Security"
TeamName: "CCCS"
Logo: "capstone/cccs-security-logo.jpg"
Overview: "Toolchain Trail is the second level of the project and builds upon the foundation established in Level 1, Identity Forge. Its purpose is to guide students through setting up and verifying a complete development environment across macOS, Windows/WSL, and Linux."
Team: ["Lucas Masterson", "Jacob Chou", "Zhengji Li"]